"""
export_to_c.py
--------------
Exports trained DirectionCNN weights to a C header file.

This generates model_weights.h which is #included by cnn_inference.c
on the Bebop. The header contains every weight and bias array as
static const float arrays, ready to use without any external libraries.

Usage
-----
    python export_to_c.py --checkpoint checkpoints/best_model.pth \
                          --output ../gate_cnn/model_weights.h

What gets exported
------------------
For each layer the following arrays are written:

  Conv layers:
    <layer>_weight   shape: [out_ch, in_ch, kH, kW]
    <layer>_bias     shape: [out_ch]

  Linear layers:
    <layer>_weight   shape: [out_features, in_features]
    <layer>_bias     shape: [out_features]

Array naming convention
-----------------------
PyTorch parameter names use dots (e.g. features.0.weight).
These are converted to underscores  (e.g. features_0_weight)
so they are valid C identifiers.

The generated header also includes a summary comment listing all
layer names and shapes so cnn_inference.c can be written to match.
"""

import os
import sys
import argparse

# model.py lives in ../src relative to this file
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.append(os.path.dirname(__file__))

import torch
from model import DirectionCNN


def write_array(f, name: str, tensor):
    """Write one float array to the header file."""
    data  = tensor.detach().cpu().numpy().flatten()
    shape = list(tensor.shape)

    f.write(f"// shape: {shape}  elements: {len(data)}\n")
    f.write(f"static const float {name}[] = {{\n")

    for i, val in enumerate(data):
        f.write(f"    {float(val):.8f}f")
        if i != len(data) - 1:
            f.write(",")
        # 8 values per line for readability
        if (i + 1) % 8 == 0 or i == len(data) - 1:
            f.write("\n")
        else:
            f.write(" ")

    f.write("};\n\n")


def main():
    args = get_args()

    # ------------------------------------------------------------------
    # Load model with trained weights
    # ------------------------------------------------------------------
    model = DirectionCNN()

    state_dict = torch.load(args.checkpoint, map_location="cpu")
    model.load_state_dict(state_dict)
    model.eval()

    print(f"Loaded checkpoint: {args.checkpoint}")

    # ------------------------------------------------------------------
    # Print layer summary so you can verify cnn_inference.c matches
    # ------------------------------------------------------------------
    print("\nLayer summary (use this to write cnn_inference.c):")
    print(f"  {'Parameter name':<35} {'C array name':<35} {'Shape'}")
    print(f"  {'-'*35} {'-'*35} {'-'*20}")

    state = model.state_dict()
    for name, tensor in state.items():
        c_name = name.replace(".", "_")
        print(f"  {name:<35} {c_name:<35} {list(tensor.shape)}")

    # ------------------------------------------------------------------
    # Write header file
    # ------------------------------------------------------------------
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("#ifndef MODEL_WEIGHTS_H\n")
        f.write("#define MODEL_WEIGHTS_H\n\n")
        f.write("/*\n")
        f.write(" * model_weights.h\n")
        f.write(" * Auto-generated by export_to_c.py — do not edit manually.\n")
        f.write(" *\n")
        f.write(" * Network: DirectionCNN\n")
        f.write(f" * Checkpoint: {args.checkpoint}\n")
        f.write(" * Input: [1, 1, 120, 160]  (grayscale, H x W)\n")
        f.write(" * Output: heading (tanh, [-1,1]), confidence (sigmoid, [0,1])\n")
        f.write(" *\n")
        f.write(" * Layer index reference for cnn_inference.c:\n")

        for name, tensor in state.items():
            c_name = name.replace(".", "_")
            f.write(f" *   {c_name:<38} {list(tensor.shape)}\n")

        f.write(" */\n\n")

        # Write every weight array
        for name, tensor in state.items():
            c_name = name.replace(".", "_")
            write_array(f, c_name, tensor)

        f.write("#endif /* MODEL_WEIGHTS_H */\n")

    print(f"\nExported to: {args.output}")

    # ------------------------------------------------------------------
    # Sanity check: count total parameters
    # ------------------------------------------------------------------
    total = sum(t.numel() for t in state.values())
    print(f"Total values written: {total:,}  "
          f"({total * 4 / 1024:.1f} KB as float32)")

    print("\n" + "=" * 50)
    print("Next step: write cnn_inference.c")
    print("  - #include \"model_weights.h\"")
    print("  - Implement conv2d, maxpool, avgpool, relu, linear")
    print("  - Call layers in order matching the summary above")
    print("=" * 50)


def get_args():
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", required=True,
                   help="Path to best_model.pth from training.")
    p.add_argument("--output",     default="model_weights.h",
                   help="Output path for the C header file.")
    return p.parse_args()


if __name__ == "__main__":
    main()