/*
 * cnn_inference.c
 * ---------------
 * Pure C forward pass for DirectionCNN.
 * No external dependencies — only math.h.
 *
 * Architecture (must match model.py exactly):
 *
 *   Input:  [1, 120, 160]   grayscale float, normalised to [0,1]
 *
 *   Conv1  (1->8,  3x3, pad=1) + ReLU    -> [8,  120, 160]
 *   Pool1  MaxPool(2x1)                   -> [8,   60, 160]
 *   Conv2  (8->16, 3x3, pad=1) + ReLU    -> [16,  60, 160]
 *   Pool2  MaxPool(2x2)                   -> [16,  30,  80]
 *   Conv3  (16->32,3x3, pad=1) + ReLU    -> [32,  30,  80]
 *   Pool3  MaxPool(2x2)                   -> [32,  15,  40]
 *   Conv4  (32->32,3x3, pad=1) + ReLU    -> [32,  15,  40]
 *   HorizPool AvgPool(15x1)              -> [32,   1,  40]  = 1280 floats
 *   FC1    Linear(1280->64) + ReLU       -> [64]
 *   FC2    Linear(64->2)                 -> [2]
 *   heading    = tanhf(out[0])
 *   confidence = sigmoidf(out[1])
 *
 * API:
 *   void cnn_run(const float *image, float *heading, float *confidence);
 *
 * Weights included from model_weights.h (auto-generated by export_to_c.py).
 */

#include "cnn_inference.h"
#include "model_weights.h"
#include <math.h>

/* ── Shape defines ───────────────────────────────────────────────────────── */
#define IN_H    120
#define IN_W    160

#define C1_OC   8
#define C2_OC   16
#define C3_OC   32
#define C4_OC   32

#define P1_H    60      /* after MaxPool(2x1): height/2 */
#define P1_W    160

#define P2_H    30      /* after MaxPool(2x2) */
#define P2_W    80

#define P3_H    15      /* after MaxPool(2x2) */
#define P3_W    40

/* After HorizPool(15x1): [32, 1, 40] -> flatten -> 1280 */
#define HP_W    40
#define FC1_IN  (C4_OC * HP_W)   /* 32 * 40 = 1280 */
#define FC1_OUT 64
#define FC2_OUT 2

/*
 * Buffer sizes — must hold the largest intermediate tensor.
 *   buf_a: largest is conv1 output = 8 * 120 * 160 = 153,600
 *   buf_b: largest is pool1 output = 8 *  60 * 160 =  76,800
 *          or conv2 output         = 16 * 60 * 160 = 153,600
 */
#define BUF_A_SIZE  153600
#define BUF_B_SIZE  153600

static float buf_a[BUF_A_SIZE];
static float buf_b[BUF_B_SIZE];
static float horiz_pool_out[FC1_IN];   /* 1280 */
static float fc1_out[FC1_OUT];         /*   64 */
static float fc2_out[FC2_OUT];         /*    2 */

/* ── Helpers ─────────────────────────────────────────────────────────────── */

static void relu_inplace(float *x, int n)
{
    for (int i = 0; i < n; i++) {
        if (x[i] < 0.0f) x[i] = 0.0f;
    }
}

/* ── Conv2d (3x3, same padding) ──────────────────────────────────────────── */

static void conv2d_same_3x3(
    const float *input,
    int          in_c,
    int          in_h,
    int          in_w,
    const float *weight,
    const float *bias,
    int          out_c,
    float       *output)
{
    for (int oc = 0; oc < out_c; oc++) {
        for (int y = 0; y < in_h; y++) {
            for (int x = 0; x < in_w; x++) {

                float sum = bias[oc];

                for (int ic = 0; ic < in_c; ic++) {
                    for (int ky = 0; ky < 3; ky++) {
                        int iy = y + ky - 1;
                        if (iy < 0 || iy >= in_h) continue;

                        for (int kx = 0; kx < 3; kx++) {
                            int ix = x + kx - 1;
                            if (ix < 0 || ix >= in_w) continue;

                            int in_idx = (ic * in_h + iy) * in_w + ix;
                            int w_idx  = ((oc * in_c + ic) * 3 + ky) * 3 + kx;
                            sum += input[in_idx] * weight[w_idx];
                        }
                    }
                }
                output[(oc * in_h + y) * in_w + x] = sum;
            }
        }
    }
}

/* ── MaxPool2d (2x1) — halves height only ────────────────────────────────── */

static void maxpool2d_2x1(
    const float *input,
    int          c,
    int          in_h,
    int          in_w,
    float       *output)
{
    int out_h = in_h / 2;

    for (int ch = 0; ch < c; ch++) {
        for (int y = 0; y < out_h; y++) {
            int iy0 = 2 * y;
            int iy1 = iy0 + 1;
            for (int x = 0; x < in_w; x++) {
                float a = input[(ch * in_h + iy0) * in_w + x];
                float b = input[(ch * in_h + iy1) * in_w + x];
                output[(ch * out_h + y) * in_w + x] = a > b ? a : b;
            }
        }
    }
}

/* ── MaxPool2d (2x2) — halves both dims ──────────────────────────────────── */

static void maxpool2d_2x2(
    const float *input,
    int          c,
    int          in_h,
    int          in_w,
    float       *output)
{
    int out_h = in_h / 2;
    int out_w = in_w / 2;

    for (int ch = 0; ch < c; ch++) {
        for (int y = 0; y < out_h; y++) {
            int iy0 = 2 * y;
            int iy1 = iy0 + 1;
            for (int x = 0; x < out_w; x++) {
                int ix0 = 2 * x;
                int ix1 = ix0 + 1;

                float v0 = input[(ch * in_h + iy0) * in_w + ix0];
                float v1 = input[(ch * in_h + iy0) * in_w + ix1];
                float v2 = input[(ch * in_h + iy1) * in_w + ix0];
                float v3 = input[(ch * in_h + iy1) * in_w + ix1];

                float m01 = v0 > v1 ? v0 : v1;
                float m23 = v2 > v3 ? v2 : v3;
                output[(ch * out_h + y) * out_w + x] = m01 > m23 ? m01 : m23;
            }
        }
    }
}

/* ── AvgPool — height only, width preserved ──────────────────────────────── */
/*
 * Input:  [c, in_h, in_w]
 * Output: [c, in_w]   (flattened — height axis is collapsed)
 *
 * Each output value is the column average for one channel.
 * Preserves horizontal position so FC can learn heading from it.
 */
static void avgpool_height_only(
    const float *input,
    int          c,
    int          in_h,
    int          in_w,
    float       *output)
{
    const float inv_h = 1.0f / (float)in_h;

    for (int ch = 0; ch < c; ch++) {
        for (int x = 0; x < in_w; x++) {
            float sum = 0.0f;
            for (int y = 0; y < in_h; y++) {
                sum += input[(ch * in_h + y) * in_w + x];
            }
            output[ch * in_w + x] = sum * inv_h;
        }
    }
}

/* ── Linear layer ────────────────────────────────────────────────────────── */

static void linear(
    const float *input,
    int          in_features,
    const float *weight,
    const float *bias,
    int          out_features,
    float       *output)
{
    for (int o = 0; o < out_features; o++) {
        float sum = bias[o];
        for (int i = 0; i < in_features; i++) {
            sum += weight[o * in_features + i] * input[i];
        }
        output[o] = sum;
    }
}

/* ── Public API ──────────────────────────────────────────────────────────── */

void cnn_run(const float *image, float *heading, float *confidence)
{
    /* Conv1 + ReLU: [1, 120, 160] -> [8, 120, 160] */
    conv2d_same_3x3(image, 1, IN_H, IN_W,
                    features_0_weight, features_0_bias, C1_OC, buf_a);
    relu_inplace(buf_a, C1_OC * IN_H * IN_W);

    /* Pool1 MaxPool(2x1): [8, 120, 160] -> [8, 60, 160] */
    maxpool2d_2x1(buf_a, C1_OC, IN_H, IN_W, buf_b);

    /* Conv2 + ReLU: [8, 60, 160] -> [16, 60, 160] */
    conv2d_same_3x3(buf_b, C1_OC, P1_H, P1_W,
                    features_3_weight, features_3_bias, C2_OC, buf_a);
    relu_inplace(buf_a, C2_OC * P1_H * P1_W);

    /* Pool2 MaxPool(2x2): [16, 60, 160] -> [16, 30, 80] */
    maxpool2d_2x2(buf_a, C2_OC, P1_H, P1_W, buf_b);

    /* Conv3 + ReLU: [16, 30, 80] -> [32, 30, 80] */
    conv2d_same_3x3(buf_b, C2_OC, P2_H, P2_W,
                    features_6_weight, features_6_bias, C3_OC, buf_a);
    relu_inplace(buf_a, C3_OC * P2_H * P2_W);

    /* Pool3 MaxPool(2x2): [32, 30, 80] -> [32, 15, 40] */
    maxpool2d_2x2(buf_a, C3_OC, P2_H, P2_W, buf_b);

    /* Conv4 + ReLU: [32, 15, 40] -> [32, 15, 40] */
    conv2d_same_3x3(buf_b, C3_OC, P3_H, P3_W,
                    features_9_weight, features_9_bias, C4_OC, buf_a);
    relu_inplace(buf_a, C4_OC * P3_H * P3_W);

    /* HorizPool AvgPool(15x1): [32, 15, 40] -> [32, 40] = 1280 floats */
    avgpool_height_only(buf_a, C4_OC, P3_H, P3_W, horiz_pool_out);

    /* FC1 Linear(1280->64) + ReLU */
    linear(horiz_pool_out, FC1_IN,
           head_1_weight, head_1_bias,
           FC1_OUT, fc1_out);
    relu_inplace(fc1_out, FC1_OUT);

    /* FC2 Linear(64->2) */
    linear(fc1_out, FC1_OUT,
           head_3_weight, head_3_bias,
           FC2_OUT, fc2_out);

    /* Activations */
    *heading    = tanhf(fc2_out[0]);
    *confidence = 1.0f / (1.0f + expf(-fc2_out[1]));
}